- name: Prepare all hosts
  hosts: all
  tasks:
    - name: Install packages
      apt:
        name: openssh-server
        update_cache: true

    - name: Adjust hosts file
      shell: >
        echo
        {{ ansible_default_ipv4.address }}
        www.domain2.test
        sub.domain2.test
        >>/etc/hosts
